# https://docs.spring.io/spring-boot/docs/2.5.1/reference/html/application-properties.html#application-properties
server:
  # http encoding
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  profiles:
    active: dev

  mvc:
    static-path-pattern: static/**
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    livereload:
      enabled: true

# 배포 시 logback-spring.xml의 scan을 true로 한다.
# 아래 외부 경로에 해당 xml file을 위치
# logback 변경 사항 발생 시 application을 재시작 않고 수정 가능하다.
# logging:
#   config: [외부 경로]
